// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqaagzcogczjyufmiwds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYWFnemNvZ2N6anl1Zm1pd2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDUzODcsImV4cCI6MjA2ODY4MTM4N30.CHOHfS8IVce5mPZdi1dWURhzBrZ_HWhtiPeF_fzT7JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});